os: linux
dist: focal

language: node_js
node_js: 14
cache: yarn
install: skip

jobs:
  include:
    - &test
      stage: test
      install: yarn
      script: yarn test
      after_script: npm run coveralls
      workspaces:
        create:
          name: shared
          paths:
            - node_modules

    - <<: *test
      if: branch = master AND type = pull_request
      os: windows
      env: YARN_GPG=no
      script: cli/synp.js -s yarn.lock
      after_script: skip
      workspaces:

    - stage: release
      if: branch = master AND type != pull_request
      workspaces:
        use: shared
      script: yarn release
